"""Initial Migration

Revision ID: 5124beb58258
Revises: 90df968025ad
Create Date: 2019-03-01 18:46:19.204681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5124beb58258'
down_revision = '90df968025ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch', sa.String(length=500), nullable=True))
    op.drop_column('pitches', 'pitches_destription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitches_destription', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'pitch')
    # ### end Alembic commands ###
