"""add routing for pitch

Revision ID: 6a25a6e0aea0
Revises: 473176f45b18
Create Date: 2019-02-27 19:33:36.169686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a25a6e0aea0'
down_revision = '473176f45b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'posted')
    # ### end Alembic commands ###
