"""add class of delete

Revision ID: 790abf3366b5
Revises: 5124beb58258
Create Date: 2019-03-05 13:07:04.633633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790abf3366b5'
down_revision = '5124beb58258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitches', sa.String(length=500), nullable=True))
    op.drop_column('pitches', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'pitches')
    # ### end Alembic commands ###
