"""add class for comment

Revision ID: 9e9ccc1feb83
Revises: 790abf3366b5
Create Date: 2019-03-05 18:35:21.130131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9ccc1feb83'
down_revision = '790abf3366b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(length=500), nullable=True))
    op.drop_column('comments', 'comments_sentences')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comments_sentences', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
