"""delete category

Revision ID: f48e1547e50c
Revises: 9e9ccc1feb83
Create Date: 2019-03-05 18:52:06.794986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48e1547e50c'
down_revision = '9e9ccc1feb83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
